import './globals.css'
import Navbar from '@/components/Navbar'
import Provider from '@/SessionProvider'


export const metadata = {
  title: 'Social Site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
      <Provider>
        <main className="bg-gray-50 min-h-screen">
          <Navbar />          
          {children}
          </main>
        </Provider>
        </body>
    </html>
  )
}
